export interface Segment {
  text: string;
  id?: string;
}

export interface Email {
  id: string;
  brand: string;
  from: string;
  replyTo?: string;
  to: string;
  subject: string;
  date: string;
  body: string[];
  suspects: string[];
  reason: Record<string, string>;
}

export function parse(line: string): Segment[] {
  const out: Segment[] = [];
  const re = /\[\[(.+?)\|(.+?)\]\]/g;
  let last = 0;
  let m: RegExpExecArray | null;
  while ((m = re.exec(line))) {
    if (m.index > last) out.push({ text: line.slice(last, m.index) });
    out.push({ id: m[1], text: m[2] });
    last = m.index + m[0].length;
  }
  if (last < line.length) out.push({ text: line.slice(last) });
  return out;
}

export const EMAILS: Email[] = [
  {
    id: 'e1',
    brand: 'GOOGLE ACCOUNTS',
    from: 'Google <[[a1|no-reply@accounts.google.com.secure-login.net]]>',
    to: 'you@college.edu',
    subject: '[[a2|Security alert]]: new sign-in on Windows',
    date: '[[a3|08/09/2026, 11:47]]',
    body: [
      'Your Google Account was just signed in on a device we have not seen before. We are letting you know so you can check it was really you.',
      'Device: [[a4|Windows 11, Chrome 128.0.6613]]',
      'Location: [[a5|Kochi, Kerala, India]]',
      'IP address: [[a6|103.48.196.24]]',
      'Time: [[a7|08/09/2026, 11:46]]',
      'If this was you, there is nothing to do. If you do not recognise this activity, [[a8|review your recent sign-ins]] and change your password.',
      'You received this because Google sends an alert every time an account is accessed from an unrecognised device. You can adjust this in [[a9|notification settings]].',
      'The Google Accounts Team',
    ],
    suspects: ['a1'],
    reason: {
      a1: 'Read a domain from the right. The owner is the last two parts before the slash — secure-login.net. "accounts.google.com" is only a subdomain the attacker was free to name whatever they liked. Google never sends from anything other than google.com.',
      a2: 'Google genuinely uses this phrase. Sounding urgent is not evidence of forgery.',
      a3: 'A real date, and it matches the timestamp in the body one minute later, which is exactly right for an alert.',
      a4: 'A plausible and current version string. Nothing here contradicts anything else.',
      a5: 'A location line is standard in these alerts, and this one matches the IP.',
      a6: 'A valid Indian IP range. Consistent with the stated location.',
      a7: 'One minute before the email was sent. That is the correct order of events.',
      a8: 'Genuine alerts do contain an action link. Link text alone proves nothing.',
      a9: 'A real Google feature, mentioned in real alerts.',
    },
  },

  {
    id: 'e2',
    brand: 'COLLEGE EXAMINATION CELL',
    from: 'Examination Cell <[[b1|examcell@college.edu]]>',
    to: 'you@college.edu',
    subject: 'Hall ticket released — [[b2|Semester 6]] regular examinations',
    date: '[[b3|30/02/2026, 16:02]]',
    body: [
      'Dear Student,',
      'The hall tickets for the [[b4|Semester 6]] regular examinations have been released. You may now download yours from the student portal using your register number and date of birth.',
      'Examinations begin on [[b5|09/03/2026]]. The last date to download the hall ticket is [[b6|05/03/2026]]. Requests received after that date will not be processed.',
      'Students with pending internal marks should contact their department office before [[b7|03/03/2026]].',
      'A printed copy must be carried to the examination hall. Digital copies on a phone will not be accepted at the gate.',
      'Reporting time is [[b8|09:00]] for the forenoon session and [[b9|13:30]] for the afternoon session.',
      'Examination Cell',
    ],
    suspects: ['b3'],
    reason: {
      b3: 'There is no 30th of February in any year. February has 28 days, or 29 in a leap year, and never 30. A mail server stamps its own send time from a real clock, so this date could not have been generated by one.',
      b1: 'The address matches the college domain exactly. No lookalike, no added subdomain.',
      b2: 'An ordinary semester reference, and it matches the subject line.',
      b4: 'Consistent with the subject.',
      b5: 'A real date, and it falls after the download deadline. The order makes sense.',
      b6: 'A real date, four days before the exams begin. Reasonable.',
      b7: 'A real date, before the download deadline. Internally consistent.',
      b8: 'A normal reporting time.',
      b9: 'A normal afternoon session time.',
    },
  },

  {
    id: 'e3',
    brand: 'HDFC BANK',
    from: 'HDFC Bank Alerts <[[c1|alerts@hdfcbank.com]]>',
    to: 'you@college.edu',
    subject: 'Debit alert: [[c2|₹8,400.00]] on card ending [[c3|4471]]',
    date: '[[c4|14/04/2026, 19:08]]',
    body: [
      'Dear Customer,',
      'A transaction of [[c5|₹8,400.00]] has been debited from your account today at [[c6|21:45]].',
      'Merchant: [[c7|NEXUS DIGITAL LTD]]',
      'Card: XXXX XXXX XXXX [[c8|4471]]',
      'Reference: [[c9|HDFC2604140819]]',
      'Available balance after this transaction: [[c10|₹12,660.00]].',
      'If you did not authorise this transaction, call the number printed on the back of your card immediately. Do not share your PIN, card number or OTP with anyone, including bank staff.',
      'HDFC Bank',
    ],
    suspects: ['c6'],
    reason: {
      c6: 'The email was sent at 19:08, but it describes a transaction at 21:45 — two hours and thirty-seven minutes later. An alert is generated after a payment clears. It cannot report something that has not happened yet.',
      c1: 'The domain is hdfcbank.com with nothing added or altered. Correct.',
      c2: 'Matches the amount in the body exactly.',
      c3: 'Matches the card number shown in the body.',
      c4: 'A real date in a consistent format.',
      c5: 'Matches the subject line.',
      c7: 'An unfamiliar merchant is suspicious to you personally, but it is not evidence the email is forged.',
      c8: 'Matches the subject line.',
      c9: 'A plausible reference format. Nothing contradicts it.',
      c10: 'A plausible balance. No other figure in the message disagrees with it.',
    },
  },

  {
    id: 'e4',
    brand: 'AMAZON',
    from: 'Amazon.in <[[d1|auto-confirm@arnazon.in]]>',
    to: 'you@college.edu',
    subject: 'Your order [[d2|#402-8871934-2210056]] has shipped',
    date: '[[d3|02/09/2026, 21:33]]',
    body: [
      'Hello,',
      'Good news — your order is on the way. You can track your package at any time from Your Orders.',
      'Item: [[d4|Logitech MX Master 3S Wireless Mouse, Graphite]]',
      'Quantity: [[d5|1]]',
      'Order total: [[d6|₹8,295.00]]',
      'Shipped via: [[d7|Amazon Transportation Services]]',
      'Track your package: [[d8|amazon.in/your-orders]]',
      'Arriving: [[d9|05/09/2026]] by 9 PM',
      'Delivering to: [[d10|Ernakulam, Kerala 682021]]',
      'Returns are accepted within [[d11|10 days]] of delivery for this item.',
    ],
    suspects: ['d1'],
    reason: {
      d1: 'Read the sender one letter at a time: a-r-n-a-z-o-n. The "m" has been replaced with "r" followed by "n", which at reading size is nearly identical. This is called a homoglyph attack and it is the single most effective trick in phishing.',
      d2: 'The order number follows the genuine 3-7-7 digit format Amazon uses.',
      d3: 'A real date, three days before the stated delivery. Reasonable.',
      d4: 'A real product with a real colour variant.',
      d5: 'Nothing to flag.',
      d6: 'A plausible price for this item.',
      d7: 'A real Amazon logistics arm.',
      d8: 'This link points at the genuine domain. The sender is the problem here, not the link.',
      d9: 'Three days after dispatch. Entirely ordinary.',
      d10: 'A real pincode for the region.',
      d11: 'A normal returns window for electronics.',
    },
  },

  {
    id: 'e5',
    brand: 'IT SERVICE DESK',
    from: 'IT Service Desk <[[f1|servicedesk@college.edu]]>',
    replyTo: '[[f2|it.helpdesk.college@gmail.com]]',
    to: 'you@college.edu',
    subject: 'Mailbox quota exceeded — action required within [[f3|48 hours]]',
    date: '[[f4|07/09/2026, 08:15]]',
    body: [
      'Dear Staff and Students,',
      'Our monitoring system shows that your mailbox has reached [[f5|98% of its allocated quota]] of [[f6|2 GB]]. Once the limit is reached you will stop receiving new mail, and messages sent to you will bounce back to the sender.',
      'We are increasing allocations in batches this week. To have your mailbox extended to [[f7|5 GB]], reply to this message with your [[f8|username and password]] so that we can apply the change to your account directly.',
      'Alternatively you may free up space by deleting large attachments from your Sent folder.',
      'Requests will be processed in the order they are received. Failure to respond may result in [[f9|temporary loss of access]] to your mailbox.',
      'Thank you for your cooperation.',
      'IT Service Desk, Ext. [[f10|4412]]',
    ],
    suspects: ['f2', 'f8'],
    reason: {
      f2: 'The From line is the genuine college domain — which is precisely what makes this work. But Reply-To silently redirects your answer to a personal Gmail account. Whatever you type goes to the attacker, not the college. Almost nobody checks this line.',
      f8: 'No IT department will ever need your password. They administer the mail server, so they can reset an account without knowing what your password was. Any message asking for one is fraudulent, whatever address it came from.',
      f1: 'This address is genuine and correctly spelled. That is why the Reply-To line matters so much here.',
      f3: 'Deadline language appears in real notices too.',
      f4: 'A real date and a normal working hour.',
      f5: 'Quota warnings are routine and this figure is plausible.',
      f6: 'A realistic institutional mailbox allocation.',
      f7: 'A realistic upgraded allocation.',
      f9: 'Consequence language is common in genuine IT notices.',
      f10: 'A plausible internal extension number.',
    },
  },
];